"use client";

import { useState } from "react";
import { X, Copy, Check, Download } from "lucide-react";
import type { AnalysisResult, CampaignSnapshot, ComputedFields } from "@/lib/schema";
import { copyToClipboard } from "@/lib/utils";

interface WeeklyMemoProps {
  result: AnalysisResult;
  snapshot: CampaignSnapshot;
  computed: ComputedFields;
  onClose: () => void;
}

function generateMemoMarkdown(
  snapshot: CampaignSnapshot,
  computed: ComputedFields,
  result: AnalysisResult
): string {
  const date = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const riskLabel =
    result.risk.riskScore <= 30
      ? "🟢 Low"
      : result.risk.riskScore <= 60
      ? "🟡 Medium"
      : "🔴 High";

  const lines: string[] = [
    `# ${snapshot.brandName} — Weekly Growth Memo`,
    `**Period:** ${snapshot.timeWindow} ending ${date}`,
    `**Industry:** ${snapshot.industry} | **Generated by:** AI Growth Operator v2`,
    "",
    "---",
    "",
    "## 📊 Performance Summary",
    "",
    result.summary.oneLiner,
    "",
    "**Key Metrics:**",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Spend | $${snapshot.metrics.spend.toLocaleString()} |`,
    `| Revenue | $${snapshot.metrics.revenue.toLocaleString()} |`,
    `| ROAS | ${computed.roas.toFixed(2)}x |`,
    `| CTR | ${snapshot.metrics.ctr}% |`,
    `| CVR | ${snapshot.metrics.conversionRate}% |`,
    `| CPM | $${snapshot.metrics.cpm} |`,
    `| AOV | $${snapshot.metrics.aov} |`,
    `| Est. CAC | $${computed.estimatedCac.toFixed(2)} |`,
    "",
    "---",
    "",
    "## 🔍 Likely Drivers",
    "",
    `**Primary Bottleneck: ${result.primaryBottleneck}** (${Math.round(result.confidence * 100)}% confidence)`,
    "",
  ];

  for (const b of result.bottlenecks) {
    lines.push(`**${b.type}** — Signal ${Math.round(b.signalStrength * 100)}%`);
    for (const r of b.reasoning) lines.push(`- ${r}`);
    lines.push("");
  }

  lines.push("---", "", "## ✅ Actions This Week", "");
  for (const a of result.actionPlan) {
    lines.push(
      `### ${a.priority}. ${a.title}`,
      `- **Expected impact:** ${a.expectedImpact}`,
      `- **Risk:** ${a.risk}`,
      ""
    );
  }

  lines.push("---", "", "## 🧪 Experiments Planned", "");
  for (const e of result.experiments) {
    lines.push(
      `### ${e.name}`,
      `*${e.hypothesis}*`,
      "",
      `**Setup:** ${e.setup}`,
      "",
      `**Success metrics:** ${e.successMetrics.join(" · ")}`,
      "",
      `**Guardrails:** ${e.guardrails.join(" · ")}`,
      ""
    );
  }

  lines.push("---", "", "## 🎨 Creative Direction", "");
  lines.push("**Angles:**");
  for (const a of result.creativeDirections.angles) lines.push(`- ${a}`);
  lines.push("", "**Hooks:**");
  for (const h of result.creativeDirections.hooks) lines.push(`- ${h}`);
  lines.push("", "**CTAs:**");
  for (const c of result.creativeDirections.ctas) lines.push(`- ${c}`);

  lines.push(
    "",
    "---",
    "",
    "## ⚠️ Risks + What We're Watching",
    "",
    `**Risk Score: ${result.risk.riskScore}/100 — ${riskLabel}**`,
    ""
  );
  for (const d of result.risk.riskDrivers) lines.push(`- ${d}`);

  lines.push("", "**Checks to Confirm:**");
  for (const c of result.checksToConfirm) lines.push(`- ${c}`);

  lines.push(
    "",
    "---",
    "",
    `*Generated by AI Growth Operator v2 · ${date}*`
  );

  return lines.join("\n");
}

export function WeeklyMemo({ result, snapshot, computed, onClose }: WeeklyMemoProps) {
  const [copied, setCopied] = useState(false);
  const memo = generateMemoMarkdown(snapshot, computed, result);

  async function handleCopy() {
    await copyToClipboard(memo);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  function handleDownload() {
    const blob = new Blob([memo], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${snapshot.brandName.toLowerCase().replace(/\s+/g, "-")}-growth-memo-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <>
      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{
          position: "fixed",
          inset: 0,
          background: "rgba(0,0,0,0.6)",
          backdropFilter: "blur(4px)",
          zIndex: 200,
        }}
      />

      {/* Modal */}
      <div
        style={{
          position: "fixed",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          zIndex: 201,
          width: "min(680px, calc(100vw - 2rem))",
          maxHeight: "88vh",
          display: "flex",
          flexDirection: "column",
          background: "var(--dropdown-bg)",
          border: "1px solid rgba(139,92,246,0.25)",
          borderRadius: "18px",
          boxShadow: "0 32px 80px rgba(0,0,0,0.6)",
          animation: "fadeInUp 0.2s ease-out",
        }}
      >
        {/* Header */}
        <div
          style={{
            padding: "1.125rem 1.375rem",
            borderBottom: "1px solid var(--border-1)",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexShrink: 0,
          }}
        >
          <div>
            <p
              style={{
                fontSize: "0.6875rem",
                color: "var(--fg3)",
                fontWeight: 600,
                letterSpacing: "0.07em",
                textTransform: "uppercase",
                margin: "0 0 0.2rem",
              }}
            >
              Client Memo
            </p>
            <h3 style={{ fontSize: "0.9375rem", fontWeight: 700, color: "var(--fg1)", margin: 0 }}>
              {snapshot.brandName} — Weekly Growth Report
            </h3>
          </div>
          <div style={{ display: "flex", gap: "0.5rem", alignItems: "center" }}>
            <button
              className="btn-ghost"
              onClick={handleCopy}
              style={{ display: "flex", alignItems: "center", gap: "0.3rem" }}
            >
              {copied ? (
                <><Check size={13} color="#34d399" /> Copied</>
              ) : (
                <><Copy size={13} /> Copy</>
              )}
            </button>
            <button
              className="btn-ghost"
              onClick={handleDownload}
              style={{ display: "flex", alignItems: "center", gap: "0.3rem" }}
            >
              <Download size={13} />
              .md
            </button>
            <button
              onClick={onClose}
              style={{
                background: "transparent",
                border: "none",
                cursor: "pointer",
                color: "var(--fg3)",
                padding: "0.25rem",
              }}
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Memo content */}
        <div style={{ flex: 1, overflowY: "auto", padding: "1.375rem" }}>
          <pre
            style={{
              fontFamily: "inherit",
              fontSize: "0.8125rem",
              color: "var(--fg2)",
              lineHeight: 1.75,
              margin: 0,
              whiteSpace: "pre-wrap",
              wordBreak: "break-word",
            }}
          >
            {memo}
          </pre>
        </div>
      </div>
    </>
  );
}
